/// <reference types="vite/client" />

declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<{}, {}, any>
  export default component
}

// amplify_outputs.json is generated by `ampx sandbox` / `ampx pipeline-deploy`.
// This declaration lets type-check pass without the file present.
declare module '*/amplify_outputs.json' {
  const outputs: Record<string, any>
  export default outputs
}
